version: "3"
services:
  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile
      command: "streamlit run app/app.py"
    ports:
      - "8501:8501"
    volumes:
      - "./src:/app"
