version: "3"
services:
  streamlit:
    build: .
    command: "streamlit run src/app.py"
    ports:
      - "8501:8501"
    volumes:
      - "./src:/usr/src/app/src"

streamlit:
    build:
      context: .
      dockerfile: ./docker/streamlit/Dockerfile
    command: streamlit run struns/main.py
    container_name: streamlit
    depends_on: 
      - db
    ports:
      - "8501:8501"
    volumes:
      - "./struns:/usr/src/app/struns"
